### ISSUE TITLE
Include document features

### ISSUE THREAD

**Issue by Sanjayrukmani** [Yuvaraj2702/Twitter-Development-applications#3]
Dear Yuvaraj,
                    It will be nice if you add document feature in the existing codes

**Comment by Yuvaraj2702** [comment]
Dear sanjay,
                    #3Thanks for your suggestion will review and the new features

**Comment by Yuvaraj2702** [comment]
Dear sanjay,
                    Documents features added. Thanks for your valuable suggestion
